### ISSUE TITLE
The sampling strategy during training

### ISSUE THREAD

**Issue by bo-miao** [z-x-yang/AOT#10]
Hi Zongxin,

May I know more details about the training strategies?

* In this paper, the sequence length is 5 during training, does it means 1 frame as reference (long-term), 1 frame as previous frame (short-term), and 3 frames as current frames to predict in a sequential manner?  
* Does the sampling of the frame indexes in sequences is the same as CFBI? If it does not, may I have some details?

Thank you.

**Comment by z-x-yang** [comment]
In AOT, we sample 5 continuous frames with a random gap of 1~3 between every two adjacent frames. No previous frame or the previous frame is the same as the reference frame from the aspect of CFBI.

**Comment by bo-miao** [comment]
Thank you for your detailed answer.

May I know the rough release date for the code？

**Comment by z-x-yang** [comment]
Before the main conference of NIPS 2021.

**Comment by bo-miao** [comment]
Thank you. And congratulations on your paper being accepted!
