### ISSUE TITLE
About the number of params of the model

### ISSUE THREAD

**Issue by zhouweii234** [z-x-yang/AOT#11]
May I ask  the number of params of  AOT-T, AOT-S, AOT-B, AOT-L?

**Comment by zhouweii234** [comment]
Does `param` written in Table 3.d represent  the number of params of the LSTT block or  the number of params of the overall model?

**Comment by z-x-yang** [comment]
The overall model.

**Comment by z-x-yang** [comment]
AOT-T: 5.7M, AOT-S: 7.0M, AOT-B/L: 8.3M.

All the modules of AOT were designed to be as lightweight as possible.
