### ISSUE TITLE
Question regarding Table 1

### ISSUE THREAD

**Issue by hkchengrex** [z-x-yang/AOT#14]
Hi, love your AOT/AOST. Excellent scalability. The open-source code is another big plus.

I was wondering what counts as "all frames" in Table 1 of AOST? Most papers don't mention whether they use 6FPS/30FPS (and they also don't release the code!) The authors of STM did say they use all the frames: https://github.com/seoungwugoh/STM/issues/3#issuecomment-568628359. HMMN uses a similar evaluation structure so it's likely also the case; KMN has no code but their baseline score matches STM so it is also likely that they use the 30 FPS version. Am I missing something here?

Cheers.

**Comment by z-x-yang** [comment]
Hi, 

It's good to hear from you. STCN is a very good open-source work for VOS.

THX for pointing out that STM used all the frames! I'll correct this in a revision of AOST. The current version is only a manuscript.

I'll try to contact the authors of HMMN and KMN to know if they used all the frames. If I cannot know the exact answers by the publication of AOST, I'll use a unique symbol to denote "Unknown" in the paper of AOST.

It's unfortunate that most papers don't mention whether they use all the frames, and many of them haven't released their code. 

Best.

**Comment by hkchengrex** [comment]
Sure. Thanks!
