### ISSUE TITLE
Multi-view object segmentation 

### ISSUE THREAD

**Issue by bigian98** [z-x-yang/AOT#15]
Hi,
I haven't explored your algorithm yet but I was wondering if it could be useful to me.
I wanted to know if this solution can also be used in a context where there are several images of the same object from multiple angles (not necessarily in order) and therefore not a video of the same.

Are there any theoretical bases that motivate this or some experiments done?

Thanks
Gianluca

**Comment by z-x-yang** [comment]
Hi Gianluca,

One of the key modules of the algorithm, the short-term attention, utilizes the inter-frame smoothness of videos to facilitate mask propagation. In other words, the order of images will affect the performance of segmentation in your cases. If the inter-frame smoothness is broken by a huge difference between two adjacent images, it's hard to say whether the results will be good or not. 

However, I suppose the algorithm will be robust to your cases by removing the short-term attention from the framework. Or, you could try some few-shot segmentation algorithms.

Best,
Zongxin
