### ISSUE TITLE
Finetuning on my own dataset

### ISSUE THREAD

**Issue by Jiakai-Zhang** [z-x-yang/AOT#17]
Hi Zongxin,

Congrats on a series of great works as well as Segment-and-Track Everything Project!

Now I am working on testing the Track Everything project on a multi-view microscopic dataset where the severe occlusions are likely happening and my target is tracking many small "black circles" like only 20 x 20 pixel size in a 1024 x 1024 full image while may have more than hundreds in a single image.

I am a bit surprised to see after some efforts, your model gave us a pretty nice result but still sometimes wrongly tracking multiple circles as the same or the mask could be kind of rough.

I guess there may be some additional finetuning work awaiting for us, though I am not the expert in this area.  My current efforts is more like exploring recent SOTA works and preparing datasets for them. Unfortunately, I can't find some way to optimize your model for tracking part (I have already finetuned SAM in our task so every frame can produce pretty nice mask but I cannot track them correctly).

Could you please give me some advice? And any plan to release code for customized dataset finetuning? I am very happy to help to test & discuss if you are interested in how well your model can work with medical & microscopic data like CT, MRI or Cryo-EM, Cryo-ET after finetuning.

Thanks in advance!

**Comment by z-x-yang** [comment]
It‘s good to hear that our project helps your work in medical segmentation.

For training or finetuning on customized datasets, you can follow the discussion in [here](https://github.com/yoxu515/aot-benchmark/issues/30) to implement. It's a relatively easy job. 

Good luck!

**Comment by Jiakai-Zhang** [comment]
Thanks for your reply, I will look into it!
