### ISSUE TITLE
About the input dimensions of Long-Term Attention 

### ISSUE THREAD

**Issue by zhouweii234** [z-x-yang/AOT#2]
![1](https://user-images.githubusercontent.com/62086490/129598429-04431efa-83e4-49f9-8d90-f5e8c7fe04ba.png)

How do you deal with the changeable input dimensions since the input dimensions of `torch.nn.MultiheadAttention` should be  fixed? Or do I have any misunderstandings about the use of  `torch.nn.MultiheadAttention` ?

**Comment by z-x-yang** [comment]
I realized the module of long-term attention by myself instead of using torch.nn.MultiheadAttention, which can't share the weights for query and key.
