### ISSUE TITLE
About the X^m_l in Long-Term Attention

### ISSUE THREAD

**Issue by zhouweii234** [z-x-yang/AOT#5]
The `X^m_l` in `Long-Term Attention` (red box in the picture) means the features output by backbone , or is it obtained through `Self-Attention` like `X^t_l` (blue box in the picture) ? 

![f6c7b3dee7040e0f661ea3138257763](https://user-images.githubusercontent.com/62086490/132440408-7b615b00-5e03-4e82-b9f8-0dc01fb844d6.png)

**Comment by z-x-yang** [comment]
Like the blue box for constructing a siamese-like structure.
