### ISSUE TITLE
Do you directly add the output feature of the backbone to the input of decoder?

### ISSUE THREAD

**Issue by zhouweii234** [z-x-yang/AOT#7]
Except the feature map output by LSTT, do you also directly add the output feature of the backbone to the input of the encoder? And do you add features with different scale from backbone to the decoder?

**Comment by z-x-yang** [comment]
The decoder is a simple FPN network, which utilizes the encoder features with different scales by shortcut connections.

**Comment by zhouweii234** [comment]
Thank you for your reply! 
I have one more question, which is the input of decoder? Only the output of LSTT (A in the picture) or output of LSTT with the output feature of the backbone (B in the picture)?

![70c368d2fbbf80f2ae879404c4bcf96](https://user-images.githubusercontent.com/62086490/132793668-ca2f85c1-3476-458a-9f1a-6ef2f725f17f.jpg)

**Comment by z-x-yang** [comment]
Like B.
