### ISSUE TITLE
The performance gains from image datasets (COCO, VOC, etc.)

### ISSUE THREAD

**Issue by bo-miao** [z-x-yang/AOT#9]
Hi,

I have read some of your great papers for VOS.

I noticed that models are usually first pre-trained on image datasets (COCO, VOC, etc.) and then trained on video datasets (DAVIS, YTB). May I know some experience or results about the performance gap that training with/without image datasets?

In addition, does the MobileNetV2 in this work pre-trained on ImageNet or trained from scratch?

Many thanks in advance.

**Comment by z-x-yang** [comment]
We just followed common settings to train AOTs. Without the pre-training on image datasets, the performance of AOT drops about 1~2% on YouTube-VOS. Not sure if using a longer training schedule or stronger augmentations can relieve the performance drop. 

The MobileNetV2 was initialized from ImageNet pre-training as commonly used.

**Comment by bo-miao** [comment]
Thank you for your answer.
